### ISSUE TITLE
I just want to know how to use it :)

### ISSUE THREAD

**Issue by BaiLanBird** [Anlominus/TeleHack#1]
I am new to shell, could you please tell me how to use it?

**Comment by AnLoMinus** [comment]
### **Hi thanks for your interest in this code.**
To run it is the same process as running:

## How to use TeleFight ?
-  [x] Starting Tool: `sh TeleFight start`
-  [x] Installing specific tool: `sh TeleFight install toolname`
-  [x] Remove TeleFight from System: `sh TeleFight remove`

TeleFight is very simple and easy to use tool, its available in both CLI and manual mode.

### CLI Mode :
`TeleFight -h` or `TeleFight help` for help.

Options :
- `TeleFight install [tool_name]` install any tool.
- `TeleFight -i [tool_name]` install any tool.
- `TeleFight search [tool_name]` search any tool.
- `TeleFight -s [tool_name]` search any tool.
- `TeleFight list` list all tools.
- `TeleFight list -a` list all tools.
- `TeleFight -l` list all tools.
- `TeleFight -l -a` list all tools.
- `TeleFight help` get help.
- `TeleFight -h` get help.
